//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SynoTFKeySDKTest.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SYNOTFKEYSDKTEST_DIALOG     102
#define IDR_MAINFRAME                   128
#define IDD_SELECTSDK_DIALOG            129
#define IDD_LOGIN_DIALOG                130
#define IDD_CHANGEPIN_DIALOG            131
#define IDD_UNLOCKPIN_DIALOG            132
#define IDD_PLAINTEXT_DIALOG            133
#define IDD_NEWDATAFILE_DIALOG          134
#define IDD_INPUTFILENAME_DIALOG        135
#define IDD_DIALOG_DEVINIT              136
#define IDC_MAINDLG_BTN_REFRESHLIST     1000
#define IDC_MAINDLG_TREE_LIST           1001
#define IDC_MAINDLG_LIST_INFO           1002
#define IDC_MAINDLG_BTN_DEVINFO         1003
#define IDC_MAINDLG_BTN_DEVINIT         1004
#define IDC_MAINDLG_BTN_SETLABEL        1005
#define IDC_MAINDLG_BTN_DEVAUTH         1006
#define IDC_MAINDLG_BTN_CHANGEAUTHKEY   1007
#define IDC_MAINDLG_BTN_OPENSESSION     1008
#define IDC_SELECTSDKDLG_COMBO_SDK      1009
#define IDC_MAINDLG_BTN_CLOSESESSION    1009
#define IDC_SELECTSDKDLG_EDIT_FILE      1010
#define IDC_MAINDLG_BTN_SESSIONINFO     1010
#define IDC_SELECTSDKDLG_BTN_OPENFILE   1011
#define IDC_MAINDLG_BTN_LOGINSESSION    1011
#define IDC_MAINDLG_BTN_LOGOUTSESSION   1012
#define IDC_MAINDLG_BTN_CHANGEPIN       1013
#define IDC_MAINDLG_BTN_UNLOCKPIN       1014
#define IDC_MAINDLG_BTN_GENKEYPAIR      1015
#define IDC_MAINDLG_BTN_IMPORTKEYPAIR   1016
#define IDC_MAINDLG_EXPORTPUBKEY        1017
#define IDC_MAINDLG_EXPORTSIGNPUBKEY    1017
#define IDC_MAINDLG_BTN_GENEXP_SESSIONKEY 1018
#define IDC_MAINDLG_BTN_GENERATEKEY     1018
#define IDC_MAINDLG_BTN_CLEARINFO       1019
#define IDC_LOGIN_COMBO_TYPE            1020
#define IDC_MAINDLG_EXPORTEXCHPUBKEY    1020
#define IDC_LOGINDLG_EDIT_PIN           1021
#define IDC_MAINDLG_BTN_SIGNVERIFY      1021
#define IDC_CHANGEPINDLG_EDIT_OLDPIN    1022
#define IDC_MAINDLG_BTN_CRYPTO          1022
#define IDC_CHANGEPINDLG_EDIT_NEWPIN    1023
#define IDC_MAINDLG_BTN_ENVENLOP        1023
#define IDC_UNLOCKPINDLG_EDIT_SOPIN     1024
#define IDC_MAINDLG_BTN_RELEASEKEY      1024
#define IDC_UNLOCKPINDLG_EDIT_NEWPIN    1025
#define IDC_PLAINTEXTDLG_EDIT_PLAIN     1026
#define IDC_PLAINTEXTDLG_COMBO_ALG      1028
#define IDC_MAINDLG_BTN_IMPORTCERT      1029
#define IDC_MAINDLG_BTN_EXPORTCERT      1030
#define IDC_NEWDATAFILEDLG_EDIT_FILENAME 1030
#define IDC_MAINDLG_BTN_ENUMFILES       1031
#define IDC_MAINDLG_BTN_CREATEFILE      1032
#define IDC_NEWDATAFILEDLG_EDIT_FILEDATA 1032
#define IDC_INPUTFILENAMEDLG_EDIT_FILENAME 1032
#define IDC_MAINDLG_BTN_READFILE        1033
#define IDC_MAINDLG_BTN_FILEINFO        1034
#define IDC_MAINDLG_CHECK_LISTENEVENT   1035
#define IDC_INITDLG_EDIT_LABEL          1038
#define IDC_INITDLG_EDIT_SOPIN          1039
#define IDC_INITDLG_EDIT_USERPIN        1040
#define IDC_INITDLG_EDIT_SOPIN_RETRYTIMES 1041
#define IDC_INITDLG_EDIT_SOPIN3         1042
#define IDC_INITDLG_EDIT_USERPIN_RETRYTIMES 1042

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1043
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
