#pragma once


////////////////// ¥ÌŒÛ¬Î∂®“Â ////////////////////////////
#define ERR_COMMON_START					0
#define ERR_COMMON_OK 						ERR_COMMON_START + 0
#define ERR_COMMON_UNKNOWN					ERR_COMMON_START + 1

#define ERR_FILE_START						100
#define ERR_FILE_V3D_NEWVERSION				ERR_FILE_START + 0
#define ERR_FILE_V3D_READHEAD    			ERR_FILE_START + 1
#define ERR_FILE_V3D_WRONGFORMAT			ERR_FILE_START + 2
#define ERR_FILE_V3D_OPENFAIL    			ERR_FILE_START + 3
#define ERR_FILE_V3D_OLDVERSION    			ERR_FILE_START + 4
#define ERR_FILE_V3D_NODATA    				ERR_FILE_START + 5

#define ERR_FILE_SAVEV3D_NODATA    			ERR_FILE_START + 6
#define ERR_FILE_SAVEV3D_OPENFILE  			ERR_FILE_START + 7
#define ERR_FILE_SAVEV3D_FAIL  				ERR_FILE_START + 8
#define ERR_FILE_SAVEV3D_HEAD    			ERR_FILE_START + 9
#define ERR_FILE_SAVEV3D_TABLE  			ERR_FILE_START + 10
#define ERR_FILE_SAVEV3D_SCENEPROPERTY  	ERR_FILE_START + 11
#define ERR_FILE_SAVEV3D_ENTITY    			ERR_FILE_START + 12
#define ERR_FILE_SAVEV3D_MESH  				ERR_FILE_START + 13
#define ERR_FILE_SAVEV3D_MATERIAL  			ERR_FILE_START + 14
#define ERR_FILE_SAVEV3D_CAMERA    			ERR_FILE_START + 15
#define ERR_FILE_SAVEV3D_LIGHT  			ERR_FILE_START + 16
#define ERR_FILE_SAVEV3D_SCENEGRAPH  		ERR_FILE_START + 17
#define ERR_FILE_SAVEV3D_OVERLAY    		ERR_FILE_START + 18
#define ERR_FILE_SAVEV3D_BUTTON  			ERR_FILE_START + 19
#define ERR_FILE_SAVEV3D_NAVIGATOR  		ERR_FILE_START + 20
#define ERR_FILE_SAVEV3D_AUDIO    			ERR_FILE_START + 21
#define ERR_FILE_SAVEV3D_CONTORLLER  		ERR_FILE_START + 22
#define ERR_FILE_SAVEV3D_ANNIMATION 		ERR_FILE_START + 23
#define ERR_FILE_SAVEV3D_BACKDROP    		ERR_FILE_START + 24
#define ERR_FILE_SAVEV3D_TEXT  				ERR_FILE_START + 25
#define ERR_FILE_SAVEV3D_TEXTURE  			ERR_FILE_START + 26
#define ERR_FILE_SAVEV3D_CLOSEFILE 			ERR_FILE_START + 27
#define ERR_FILE_SAVEV3D_FALSH  			ERR_FILE_START + 28


#define ERR_FILE_N3D_SAVE    				ERR_FILE_START + 50
#define ERR_FILE_N3D_LOAD                   ERR_FILE_START + 51
#define ERR_FILE_N3D_SCENELOAD              ERR_FILE_START + 52
#define ERR_FILE_N3D_IMAGELOAD              ERR_FILE_START + 53
#define ERR_FILE_N3D_VERSIONLOW             ERR_FILE_START + 54
#define ERR_FILE_N3D_VERSIONHIGH            ERR_FILE_START + 55

#define ERR_FILE_E3D_SAVE    				ERR_FILE_START + 100
#define ERR_FILE_E3D_LOAD    				ERR_FILE_START + 101
#define ERR_FILE_E3D_LOWVER    				ERR_FILE_START + 102
#define ERR_FILE_E3D_FORMAT    				ERR_FILE_START + 103   


#define ERR_FILE_OPENFAIL    				ERR_FILE_START + 200
#define ERR_FILE_READBYTEFAIL    			ERR_FILE_START + 101


#define ERR_SCENE_START                     300
#define ERR_SCENE_NOSCENE                   ERR_SCENE_START + 0
#define ERR_SCENE_CREATE                    ERR_SCENE_START + 1


#define Err_Model_Start						400

#define Err_Material_Start					500

#define Err_Camera_Start					600

#define Err_Light_Start						700
